# Generated by Django 5.1.4 on 2026-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='excel_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
