# Generated by Django 5.1.4 on 2026-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_note_remove_tracker_excel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('entry_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('mood', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
