# Generated by Django 5.1.4 on 2026-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('category_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='blue', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('habit_id', 'date')},
            },
        ),
    ]
